export const compras = [
    {
      id: 1,
      nome: "Chainsaw Man Vol. 13",
      preco: 27.68,
      categoria: "Livro",
      marca: "Planet Manga",
      cor: "Amarelo",
    },
    {
      id: 2,
      nome: "Smartwatch X-200",
      preco: 199.99,
      categoria: "Eletrônicos",
      marca: "TechGear",
      cor: "Preto",
    },
    {
      id: 3,
      nome: "Tênis Corrida Speedster",
      preco: 120.5,
      categoria: "Calçados",
      marca: "FastFeet",
      cor: "Azul",
    },
    {
      id: 4,
      nome: "Câmera ProShot 4K",
      preco: 879.9,
      categoria: "Fotografia",
      marca: "LensMaster",
      cor: "Cinza",
    },
    {
      id: 5,
      nome: "Mochila Montanhismo Adventure 60L",
      preco: 145.3,
      categoria: "Acessórios de Viagem",
      marca: "OutdoorPro",
      cor: "Verde",
    },
    {
      id: 6,
      nome: "Conjunto de Facas Chef Premium",
      preco: 260.0,
      categoria: "Utensílios de Cozinha",
      marca: "CulinaryArt",
      cor: "Inox",
    },
    {
      id: 7,
      nome: "Fone de Ouvido Bluetooth BeatSound",
      preco: 85.99,
      categoria: "Acessórios de Áudio",
      marca: "AudioTech",
      cor: "Vermelho",
    },
    {
      id: 8,
      nome: "Notebook Dell Inspiron 15 3000",
      preco: 3999.99,
      categoria: "Eletrônicos",
      marca: "Dell",
      cor: "Cinza",
    },
    {
      id: 9,
      nome: "Liquidificador Arno Power Mix 1000W",
      preco: 249.99,
      categoria: "Utensílios de Cozinha",
      marca: "Arno",
      cor: "Preto",
    },
    {
      id: 10,
      nome: "Geladeira Brastemp Frost Free Duplex Inverse 375L",
      preco: 4499.0,
      categoria: "Eletrodomésticos",
      marca: "Brastemp",
      cor: "Inox",
    },
    {
      id: 11,
      nome: "Óculos de Sol VisionPro Polarizado",
      preco: 98.75,
      categoria: "Acessórios",
      marca: "SunRay",
      cor: "Marrom",
    },
    {
      id: 12,
      nome: "Batedeira Planetária MixMaster 500W",
      preco: 320.45,
      categoria: "Utensílios de Cozinha",
      marca: "KitchenTech",
      cor: "Vermelho",
    },
    {
      id: 13,
      nome: "Jaqueta Corta Vento Explorer",
      preco: 180.99,
      categoria: "Vestuário",
      marca: "OutdoorGear",
      cor: "Preto",
    },
    {
      id: 14,
      nome: "Bicicleta Mountain Bike Xtreme",
      preco: 1500.0,
      categoria: "Esportes",
      marca: "BikePro",
      cor: "Verde",
    },
    {
      id: 15,
      nome: "Teclado Mecânico Gamer RGB",
      preco: 299.9,
      categoria: "Acessórios de Computador",
      marca: "KeyMaster",
      cor: "Azul",
    },
    {
      id: 16,
      nome: "Mala de Viagem Rodinhas 360° - 70L",
      preco: 250.0,
      categoria: "Acessórios de Viagem",
      marca: "TravelWorld",
      cor: "Cinza",
    },
    {
      id: 17,
      nome: "Relógio Analógico Classic Elegance",
      preco: 450.0,
      categoria: "Acessórios",
      marca: "Timeless",
      cor: "Dourado",
    },
    {
      id: 18,
      nome: "Perfume Elegance Femme 100ml",
      preco: 320.0,
      categoria: "Perfumaria",
      marca: "ScentArt",
      cor: "Transparente",
    },
    {
      id: 19,
      nome: "Conjunto de Panelas Antiaderente - 6 Peças",
      preco: 359.99,
      categoria: "Utensílios de Cozinha",
      marca: "CookMaster",
      cor: "Inox",
    },
    {
      id: 20,
      nome: "Smart TV 4K UHD 50' - Android TV",
      preco: 2899.99,
      categoria: "Eletrônicos",
      marca: "VisionTech",
      cor: "Preto",
    },
    {
      id: 21,
      nome: "Livro 'As Aventuras de Sherlock Holmes'",
      preco: 45.9,
      categoria: "Livro",
      marca: "ClassicReads",
      cor: "Verde",
    },
  ];